30_MVC_CRUD_Repository_Pattern/Models/Cliente.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace _30_MVC_CRUD_Repository_Pattern.Models
{
    //Define a classe como uma entidade mapeada para a tabela "tb_cliente" utilizando o entity framework
    [Table("tb_cliente")]
    public class Cliente
    {
        // Define a propriedade "Id" como a chave primária da tabela
        [Key]
        public int Id { get; set; }

        // Define a propriedade "Nome" como obrigatória e com tamanho máximo de 100 caracteres
        [Required, MaxLength(100)]
        public string Nome { get; set; }

        public int Idade { get; set; }
    }
}

30_MVC_CRUD_Repository_Pattern/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;

namespace _30_MVC_CRUD_Repository_Pattern.Models
{
    //Criando a classe de contexto, que é responsavel por conectar com banco de dados e gerenciar as transações
    public class Contexto : DbContext
    {
        public Contexto(DbContextOptions<Contexto> options) : base(options)
        {

        }


        //Criando os DBSets que são responsáveis por criar e executar as consultas de CRUD com banco, sendo Select, Update, Insert e Delete
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Pedido> Pedidos { get; set; }
    }

    //README

    /*
        Para executa a migration deve utilizar o "Package Manager Console", caso ele não esteja disponivel 
        vá no menu "View>Other Windows>Package Manager Console"


        Execute os comandos Add-Migration e Update-Database para criar a migration e depois atualizar o banco de dados.

        Add-Migration initdb  

        Update-Database
      
     */
}

30_MVC_CRUD_Repository_Pattern/Models/ErrorViewModel.cs
namespace _30_MVC_CRUD_Repository_Pattern.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

30_MVC_CRUD_Repository_Pattern/Models/Pedido.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace _30_MVC_CRUD_Repository_Pattern.Models
{
    // Define a classe como uma entidade mapeada para a tabela "tb_pedido"
    [Table("tb_pedido")]
    public class Pedido
    {
        // Define a propriedade "Id" como a chave primária da tabela
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        public decimal Valor { get; set; }
    }
}

30_MVC_CRUD_Repository_Pattern/Controllers/ClienteController.cs
using _30_MVC_CRUD_Repository_Pattern.Models;
using _30_MVC_CRUD_Repository_Pattern.Repository;
using Microsoft.AspNetCore.Mvc;

namespace _30_MVC_CRUD_Repository_Pattern.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepository _clienteRepository;

        public ClienteController(IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
        }

        public IActionResult Index()
        {
            var clientes = _clienteRepository
                .ListarTodos();

            return View(clientes);
        }

        public IActionResult Detail(int id)
        {
            var cliente = _clienteRepository
                .ObterUm(id);

            return View(cliente);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente model)
        {
            if (ModelState.IsValid)
            {
                _clienteRepository
                    .SalvarCliente(model);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteRepository.ObterUm(id ?? 0);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Edit(int id, Cliente model)
        {
            if (ModelState.IsValid)
            {
                model.Id = id;

                _clienteRepository.EditarCliente(id, model);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = _clienteRepository.ObterUm(id ?? 0);

            return View(cliente);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _clienteRepository.ExcluirCliente(id);
            return RedirectToAction("Index");
        }
    }
}

30_MVC_CRUD_Repository_Pattern/Controllers/HomeController.cs
using _30_MVC_CRUD_Repository_Pattern.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace _30_MVC_CRUD_Repository_Pattern.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

30_MVC_CRUD_Repository_Pattern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _30_MVC_CRUD_Repository_Pattern</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_30_MVC_CRUD_Repository_Pattern.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_30_MVC_CRUD_Repository_Pattern</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - _30_MVC_CRUD_Repository_Pattern - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>